#!/usr/bin/python

import click
import json
import requests
import sys
import time
import urllib

BASEURL='https://pagure.io'


def pcall(path, query=None, api=0, baseurl=BASEURL):
    url = "%s/api/%s/%s" % (baseurl, api, path)
    if isinstance(query, basestring):
        url = "%s?%s" % (url, query)
    elif query != None:
        query = urllib.urlencode(query)
        url = "%s?%s" % (url, query)
    print "DEBUG: %s" % url
    r = requests.get(url)
    try:
        data = r.json()
    except Exception:
        print "Server returned bad value"
        print r
        raise
    if 'error_code' in data:
        print "%(error_code)s: %(error)s" % data
        sys.exit(1)
    return data


@click.group()
def pg():
    # main command
    pass


@pg.command()
@click.argument('prid')
def ppr(prid):
    pr = pcall('/koji/pull-request/%s' % prid)
    import pprint; pprint.pprint(pr)

    for comment in pr['comments']:
        cts = float(comment['date_created'])
        comment['_username'] = comment['user']['name']
        comment['_tstr'] = time.asctime(time.localtime(float(cts)))
        print "Comment by %(_username)s on %(_tstr)s:" % comment
        print
        print comment['comment']
        print

    print "PR#%(id)i: %(title)s" % pr
    print
    print "Merges #%(id)i" % pr
    print "https://pagure.io/koji/pull-request/%(id)i" % pr
    print
    print "STATUS: %(status)s" % pr
    if pr.get('repo_from'):
        # should we use fullname field?
        # or 
        print "Fork: %s/%s" % (BASEURL, pr['repo_from']['fullname'])
    elif pr.get('remote_git'):
        print "Remote: %(remote_git)s" % pr
    else:
        print "Can't determine repo?"
        sys.exit(1)
    print "%(branch_from)s -> %(branch)s" % pr
    if pr['status'] != 'Open':
        print '...'


@pg.command()
@click.option('-o', '--order', default='updated_on')
def prs(order):
    data = pcall('koji/pull-requests')
    count = data['total_requests']
    prs = data['requests']
    if order:
        o_keys = order.split(',')
        def sortkey(pr):
            return [pr.get(k) for k in o_keys]
        prs.sort(key=sortkey)
    for pr in prs:
        print "PR#%(id)i: %(title)s [%(status)s]" % pr


@pg.command(name='list-projects')
@click.argument('pattern')
@click.option('--fork/--no-fork', default=False)
def list_projects(pattern, **opts):
    if pattern:
        opts['pattern'] = pattern
    data = pcall('projects', opts)
    count = data['total_projects']
    for proj in data['projects']:
        print "%(id)5i: %(name)s: %(description)s" % proj


if __name__ == '__main__':
    pg()
